In [94]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [96]:
df = pd.read_csv('combined_algo.csv')

to_drop = ["dimensions"]
ndf = df.drop(columns=to_drop)

rename =  {
               #'product_id': 'product_id',
               #'aisle_id': 'location',
               'department_id': 'product_type',
               #'add_to_cart_order': 'demand',
               #'stock': 'stock'
          }

ndf.rename(columns=rename, inplace=True)
ndf.head

<bound method NDFrame.head of          product_id  location  product_type  demand  stock
0             49688        73            11      24     30
1                 1        61            19      32     21
2                 1        61            19      32     35
3                 1        61            19      32     22
4                 1        61            19      32     22
...             ...       ...           ...     ...    ...
1345490           1        61            19      32     27
1345491           1        61            19      32     35
1345492           1        61            19      32     21
1345493           1        61            19      32     35
1345494           1        61            19      32     22

[1345495 rows x 5 columns]>

In [97]:
X = df.drop(columns=['location']).values
y = df['location'].values
X

array([[49688,    11,    24,    30],
       [    1,    19,    32,    21],
       [    1,    19,    32,    35],
       ...,
       [    1,    19,    32,    21],
       [    1,    19,    32,    35],
       [    1,    19,    32,    22]], dtype=int64)

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
X_train

array([[ 10,   7,   1,  33],
       [  1,  19,  32,  38],
       [130,   1,  68,  37],
       ...,
       [  1,  19,  32,  23],
       [ 10,   7,   1,  35],
       [ 25,  19,  92,  33]], dtype=int64)

In [99]:
regressor = DecisionTreeRegressor()
regressor.fit(X_train.reshape(-1,4), y_train.reshape(-1,1))

DecisionTreeRegressor()

In [132]:
y_pred = regressor.predict(X_test.reshape(-1,4))
score=accuracy_score(y_test.reshape(-1,1), y_pred)
score

0.999996283895518

In [128]:
pre = regressor.predict([[20,81,90,109]])
pre

array([1.])

In [102]:
rp = pd.DataFrame({'Real Values':y_test.reshape(-1), 'Predicted Values':y_pred.reshape(-1)})
rp

Real Values  Predicted Values
0                61              61.0
1               115             115.0
2                61              61.0
3               121             121.0
4                61              61.0
...             ...               ...
269094           93              93.0
269095           61              61.0
269096           61              61.0
269097           61              61.0
269098           83              83.0

[269099 rows x 2 columns]